<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>WBall.Application</AssemblyName>
    <RootNamespace>WBall</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\WBall.Core.csproj" />
  </ItemGroup>

</Project>
