<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>WBallFastVerify</AssemblyName>
    <RootNamespace>WBall.FastVerify</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\b-Code-WBall\Application\WBall.Application.csproj" />
    <ProjectReference Include="..\..\b-Code-WBall\Core\WBall.Core.csproj" />
  </ItemGroup>

</Project>
